import { useStore } from "@/lib/hooks/useStore";
import { Alert, Snackbar, Stack } from "@mui/material";
import { observer } from "mobx-react-lite";
import Head from "next/head";
import Actions from "./components/Actions";
import ClientsDialog from "./components/ClientsDialog";
import Table from "./components/Table";

import styles from "./styles.module.scss";

const Clients = () => {
  const { clientsController } = useStore();
  const { copyNotificationOpen, setCopyNotificationOpen } = clientsController;

  return (
    <>
      <Head>
        <title>Clients list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        gap="1rem"
        height="100vh"
        sx={{ overflowY: "hidden" }}
        paddingTop="1rem"
      >
        <Actions />
        <Table />
      </Stack>
      <ClientsDialog />
      <Snackbar
        open={copyNotificationOpen}
        autoHideDuration={1500}
        onClose={() => setCopyNotificationOpen(false)}
      >
        <Alert
          onClose={() => setCopyNotificationOpen(false)}
          severity="success"
          sx={{ width: "100%" }}
        >
          Скопировано в буфер
        </Alert>
      </Snackbar>
    </>
  );
};

export default observer(Clients);
